"""
Python Zebra ZPL II Library
"""

from .driver import (
    Zebra,
    ZebraBitmap,
    JUSTIFICATION_CENTRE,
    JUSTIFICATION_LEFT,
    JUSTIFICATION_RIGHT,
    JUSTIFICATION_JUSTIFIED,
    FONT_ENCODING_USA_1,
    FONT_ENCODING_USA_2,
    FONT_ENCODING_UK,
    FONT_ENCODING_HOLLAND,
    FONT_ENCODING_DENMARK_NORWAY,
    FONT_ENCODING_SWEDEN_FINLAND,
    FONT_ENCODING_GERMANY,
    FONT_ENCODING_FRANCE_1,
    FONT_ENCODING_FRANCE_2,
    FONT_ENCODING_ITALY,
    FONT_ENCODING_SPAIN,
    FONT_ENCODING_MISC_SINGLE_BYTE,
    FONT_ENCODING_JAPAN_ASCII,
    FONT_ENCODING_CODE_PAGE_850,
    FONT_ENCODING_DOUBLE_BYTE_ASIAN,
    FONT_ENCODING_SHIFT_JIS,
    FONT_ENCODING_EUC_JP_EUC_CN,
    FONT_ENCODING_DEPRECATED_UCS_2_BIG_ENDIAN,
    FONT_ENCODING_SINGLE_BYTE_ASIAN,
    FONT_ENCODING_MULTIBYTE_ASIAN_WITH_TRANSPARENCY,
    FONT_ENCODING_CODE_PAGE_1252,
    FONT_ENCODING_UTF8,
    FONT_ENCODING_UTF16_BIG_ENDIAN,
    FONT_ENCODING_UTF16_LITTLE_ENDIAN,
    FONT_ENCODING_CODE_PAGE_1250,
    FONT_ENCODING_CODE_PAGE_1251,
    FONT_ENCODING_CODE_PAGE_1253,
    FONT_ENCODING_CODE_PAGE_1254,
    FONT_ENCODING_CODE_PAGE_1255,
    ORIENTATION_0,
    ORIENTATION_90,
    ORIENTATION_180,
    ORIENTATION_270
)

__author__ = 'Stephen Brown (Little Fish Solutions LTD)'

